### ISSUE TITLE
Content Checklist:

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#70]
Prototypal Site Content

###   Index
- [ ] Hero image x1
- [ ] Grid section x9
- [ ] Ember Training x1 (eric.png)
- [ ] Want to work with us? X1

### Company
- [ ] Our story - img x1
- [ ] Our story - copy
- [ ] Our process - copy
- [ ] Meet our team - img x3
- [ ] Team member bio’s

### Training
- [ ] Below host an event  x5
- [ ] Meet our trainers x3
